Vagrant.configure("2") do |config|
  config.vm.box = "smartos-base1310-64-virtualbox-20130806.box"
  config.vm.box_url = "http://dlc-int.openindiana.org/aszeszo/vagrant/smartos-base1310-64-virtualbox-20130806.box"
end